/*
DROP TABLE F15_GOLS_CARTOES;
DROP TABLE F14_TRANSMITE;
DROP TABLE F13_APITA;
DROP TABLE F12_PATROCINA;
DROP TABLE F11_PARTIDA;
DROP TABLE F10_EMISSORA;
DROP TABLE F09_ESTADIO;
DROP TABLE F08_CAMPEONATO;
DROP TABLE F07_ARBITRO;
DROP TABLE F06_PATROCINADOR;
DROP TABLE F05_JOGADOR;
DROP TABLE F04_TIME;
DROP TABLE F03_TECNICO;
DROP TABLE F02_CIDADE;
DROP TABLE F01_ESTADO;

DROP SYNONYM F01;
DROP SYNONYM F02;
DROP SYNONYM F03;
DROP SYNONYM F04;
DROP SYNONYM F05;
DROP SYNONYM F06;
DROP SYNONYM F07;
DROP SYNONYM F08;
DROP SYNONYM F09;
DROP SYNONYM F10;
DROP SYNONYM F11;
DROP SYNONYM F12;
DROP SYNONYM F13;
DROP SYNONYM F14;
DROP SYNONYM F15;

DROP SYNONYM GOLS;
DROP SYNONYM CARTOES;
DROP SYNONYM TRANSMITE;
DROP SYNONYM APITA;
DROP SYNONYM PATROCINA;
DROP SYNONYM PARTIDA;
DROP SYNONYM EMISSORA;
DROP SYNONYM ESTADIO;
DROP SYNONYM CAMPEONATO;
DROP SYNONYM ARBITRO;
DROP SYNONYM PATROCINADOR;
DROP SYNONYM JOGADOR;
DROP SYNONYM TTIME;
DROP SYNONYM TECNICO;
DROP SYNONYM CIDADE;
DROP SYNONYM ESTADO;
*/


CREATE TABLE F01_ESTADO
(
 SIGLA CHAR(2),
 ESTADO VARCHAR2(100) NOT NULL,
 
 CONSTRAINT PK_ESTADO PRIMARY KEY(SIGLA),
 CONSTRAINT UN_ESTADO UNIQUE(ESTADO)
);

CREATE TABLE F02_CIDADE
(
 CIDADE VARCHAR(100),
 SIGLAC CHAR(2),
 
 CONSTRAINT PK_CIDADE PRIMARY KEY(CIDADE,SIGLAC),
 CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY(SIGLAC) REFERENCES F01_ESTADO(SIGLA)
);

CREATE TABLE F03_TECNICO
(
 CPFT NUMBER(8),
 TECNICO VARCHAR2(100) NOT NULL,
 
 CONSTRAINT PK_TECNICO PRIMARY KEY(CPFT),
 CONSTRAINT UN_TECNICO UNIQUE(TECNICO)
);

CREATE TABLE F04_TIME
(
 TTIME VARCHAR2(100), --TTIME para diferenciar da palavra chave TIME
 ANOFUNDACAO NUMBER(4),
 CIDADE VARCHAR(100) NOT NULL,
 ESTADO CHAR(2) NOT NULL,
 CPFT NUMBER(8),
 
 CONSTRAINT PK_TIME PRIMARY KEY(TTIME),
 CONSTRAINT FK_TIME_CIDADE FOREIGN KEY(CIDADE,ESTADO) REFERENCES F02_CIDADE(CIDADE,SIGLAC),
 CONSTRAINT FK_TIME_TECNICO FOREIGN KEY(CPFT) REFERENCES F03_TECNICO(CPFT)
);

CREATE TABLE F05_JOGADOR
(
 CPFJ NUMBER(8),
 JOGADOR VARCHAR2(100) NOT NULL,
 POSICAO VARCHAR(40),
 TTIMEJ VARCHAR2(100),
 
 CONSTRAINT PK_JOGADOR PRIMARY KEY(CPFJ),
 CONSTRAINT FK_JOGADOR_TIME FOREIGN KEY(TTIMEJ) REFERENCES F04_TIME(TTIME) ON DELETE SET NULL,
 CONSTRAINT CH_JOGADOR CHECK (POSICAO IN ('GOLEIRO', 'ZAGUEIRO', 'LATERAL', 'MEIO-CAMPO', 'ATACANTE')),
 CONSTRAINT UN_JOGADOR UNIQUE(JOGADOR)
);

CREATE TABLE F06_PATROCINADOR
(
 IDPAT NUMBER(2),
 PATROCINADOR VARCHAR2(100) NOT NULL,
 SLOGAN VARCHAR2(200),
 
 CONSTRAINT PK_PATROCINADOR PRIMARY KEY(IDPAT),
 CONSTRAINT UN_PATROCINADOR UNIQUE(PATROCINADOR)
);

CREATE TABLE F07_ARBITRO
(
 CPFA NUMBER(8),
 ARBITRO VARCHAR(100) NOT NULL,
 
 CONSTRAINT PK_ARBITRO PRIMARY KEY(CPFA),
 CONSTRAINT UN_ARBITRO UNIQUE(ARBITRO)
);

CREATE TABLE F08_CAMPEONATO
(
 IDCAMPEONATO NUMBER(2),
 CAMPEONATO VARCHAR2(100) NOT NULL,
 ANO NUMBER(4) NOT NULL,
 
 CONSTRAINT PK_CAMPEONATO PRIMARY KEY(IDCAMPEONATO),
 CONSTRAINT UN_CAMPEONATO UNIQUE(CAMPEONATO, ANO) 
);

CREATE TABLE F09_ESTADIO
(
 IDESTADIO NUMBER(2),
 ESTADIO VARCHAR2(100),
 CIDADE VARCHAR(100) NOT NULL,
 ESTADO CHAR(2) NOT NULL,
 CAPACIDADE NUMBER(6),
 
 CONSTRAINT PK_ESTADIO PRIMARY KEY(IDESTADIO),
 CONSTRAINT UN_ESTADIO UNIQUE(ESTADIO),
 CONSTRAINT FK_ESTADIO_CIDADE FOREIGN KEY(CIDADE, ESTADO) REFERENCES F02_CIDADE(CIDADE,SIGLAC)
);

CREATE TABLE F10_EMISSORA
(
 IDEMISSORA NUMBER(2),
 EMISSORA VARCHAR2(100),
 TIPO CHAR(1) NOT NULL,
 FREQUENCIA NUMBER(4,1),
 CANAL NUMBER(3),
 CUSTO_MINUTO NUMBER(10,2),
 
 CONSTRAINT PK_EMISSORA PRIMARY KEY(IDEMISSORA),
 CONSTRAINT UN_EMISSORA UNIQUE(EMISSORA),
 CONSTRAINT CH_EMISSORA CHECK((TIPO = 'R' AND FREQUENCIA IS NOT NULL) OR (TIPO = 'T' AND CANAL IS NOT NULL))
);

CREATE TABLE F11_PARTIDA
(
 IDPARTIDA NUMBER(4),
 TTIME1 VARCHAR2(100) NOT NULL, --time da casa
 TTIME2 VARCHAR2(100) NOT NULL, --time visitante 
 DATAHORA DATE NOT NULL,
 IDCAMPEONATOP NUMBER(2) NOT NULL, 
 IDESTADIOP NUMBER(2) NOT NULL,
 GOLS_TIME1 NUMBER(2) DEFAULT 0 NOT NULL,
 GOLS_TIME2 NUMBER(2) DEFAULT 0 NOT NULL,
 
 CONSTRAINT PK_PARTIDA PRIMARY KEY(IDPARTIDA),
 CONSTRAINT UN_PARTIDA UNIQUE(TTIME1,TTIME2,DATAHORA),
 CONSTRAINT FK_TTIME1 FOREIGN KEY(TTIME1) REFERENCES F04_TIME(TTIME),
 CONSTRAINT FK_TTIME2 FOREIGN KEY(TTIME2) REFERENCES F04_TIME(TTIME), 
 CONSTRAINT FK_PARTIDA_CAMP FOREIGN KEY(IDCAMPEONATOP) REFERENCES F08_CAMPEONATO(IDCAMPEONATO) ON DELETE CASCADE,
 CONSTRAINT FK_PARTIDA_ESTAD FOREIGN KEY(IDESTADIOP) REFERENCES F09_ESTADIO(IDESTADIO) ON DELETE SET NULL
);

CREATE TABLE F12_PATROCINA
(
 IDPAT NUMBER(2),
 TTIME VARCHAR2(100),
 CONTRATO BLOB,
 INICIO_VIGENCIA NUMBER(4),
 TEMPO_VIGENCIA NUMBER(3),
 
 CONSTRAINT PK_PATROCINA PRIMARY KEY(IDPAT, TTIME),
 CONSTRAINT FK_PATROCINA_PAT FOREIGN KEY(IDPAT) REFERENCES F06_PATROCINADOR(IDPAT),
 CONSTRAINT FK_PATROCINA_TIME FOREIGN KEY(TTIME) REFERENCES F04_TIME(TTIME)
);

CREATE TABLE F13_APITA
(
 CPFA NUMBER(8),
 IDPARTIDA NUMBER(4),
 FUNCAO VARCHAR2(50) NOT NULL,
 
 CONSTRAINT PK_APITA PRIMARY KEY(CPFA,IDPARTIDA),
 CONSTRAINT FK_APITA_ARBITRO FOREIGN KEY(CPFA) REFERENCES F07_ARBITRO(CPFA),
 CONSTRAINT FK_APITA_PARTIDA FOREIGN KEY(IDPARTIDA) REFERENCES F11_PARTIDA(IDPARTIDA) ON DELETE CASCADE,
 CONSTRAINT CH_FUNCAO CHECK(FUNCAO IN ('PRINCIPAL','BANDEIRINHA','RESERVA'))
);

CREATE TABLE F14_TRANSMITE
(
 IDEMISSORA NUMBER(2),
 IDPARTIDA NUMBER(4),
 
 CONSTRAINT PK_TRANSMITE PRIMARY KEY(IDEMISSORA, IDPARTIDA),
 CONSTRAINT FK_TRANSMITE_EMISS FOREIGN KEY(IDEMISSORA) REFERENCES F10_EMISSORA(IDEMISSORA),
 CONSTRAINT FK_TRANSMITE_PART FOREIGN KEY(IDPARTIDA) REFERENCES F11_PARTIDA(IDPARTIDA) ON DELETE CASCADE
);

CREATE TABLE F15_GOLS_CARTOES(
  CPFJ NUMBER(8),
  IDPARTIDA NUMBER(4),
  AMARELO CHAR(1) DEFAULT 0 NOT NULL,
  VERMELHO CHAR(1) DEFAULT 0 NOT NULL,
  GOLS NUMBER(2) DEFAULT 0 NOT NULL,
  GOLS_CONTRA NUMBER(2) DEFAULT 0 NOT NULL,
  
  CONSTRAINT PK_GOLS_CARTOES PRIMARY KEY(CPFJ, IDPARTIDA),
  CONSTRAINT FK_GOLS_CARTOES_JOGADOR FOREIGN KEY(CPFJ) REFERENCES F05_JOGADOR(CPFJ),
  CONSTRAINT FK_GOLS_CARTOES_PARTIDA FOREIGN KEY(IDPARTIDA) REFERENCES F11_PARTIDA(IDPARTIDA),
  CONSTRAINT CH_CARTOES CHECK(AMARELO IN (0,1) AND VERMELHO IN (0,1))
);

CREATE SYNONYM F15 FOR F15_GOLS_CARTOES;
CREATE SYNONYM F14 FOR F14_TRANSMITE;
CREATE SYNONYM F13 FOR F13_APITA;
CREATE SYNONYM F12 FOR F12_PATROCINA;
CREATE SYNONYM F11 FOR F11_PARTIDA;
CREATE SYNONYM F10 FOR F10_EMISSORA;
CREATE SYNONYM F09 FOR F09_ESTADIO;
CREATE SYNONYM F08 FOR F08_CAMPEONATO;
CREATE SYNONYM F07 FOR F07_ARBITRO;
CREATE SYNONYM F06 FOR F06_PATROCINADOR;
CREATE SYNONYM F05 FOR F05_JOGADOR;
CREATE SYNONYM F04 FOR F04_TIME;
CREATE SYNONYM F03 FOR F03_TECNICO;
CREATE SYNONYM F02 FOR F02_CIDADE;
CREATE SYNONYM F01 FOR F01_ESTADO;

CREATE SYNONYM GOLS FOR F15_GOLS_CARTOES;
CREATE SYNONYM CARTOES FOR F15_GOLS_CARTOES;
CREATE SYNONYM TRANSMITE FOR F14_TRANSMITE;
CREATE SYNONYM APITA FOR F13_APITA;
CREATE SYNONYM PATROCINA FOR F12_PATROCINA;
CREATE SYNONYM PARTIDA FOR F11_PARTIDA;
CREATE SYNONYM EMISSORA FOR F10_EMISSORA;
CREATE SYNONYM ESTADIO FOR F09_ESTADIO;
CREATE SYNONYM CAMPEONATO FOR F08_CAMPEONATO;
CREATE SYNONYM ARBITRO FOR F07_ARBITRO;
CREATE SYNONYM PATROCINADOR FOR F06_PATROCINADOR;
CREATE SYNONYM JOGADOR FOR F05_JOGADOR;
CREATE SYNONYM TTIME FOR F04_TIME;
CREATE SYNONYM TECNICO FOR F03_TECNICO;
CREATE SYNONYM CIDADE FOR F02_CIDADE;
CREATE SYNONYM ESTADO FOR F01_ESTADO;